apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: rancher
spec:
  type: NodePort
  selector:
    app: rancher
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30001