apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-ubuntu
  template:
    metadata:
      labels:
        name: rancher-ubuntu
        app: rancher
    spec:
      containers:
        - name: rancher-ubuntu
          image: ubuntu
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8989
